package mx.sisati.sisatibackend.espacios.caracteristicas;

public enum CaracteristicaNombre {
    REFRIGERADO,
    SIN_VENTANAS_EXTERNAS,
    CLIMATIZACION,
    VENTILACION_NATURAL,
    ILUMINACION_CALIDA,
    ILUMINACION_REGULABLE,
    TEMPERATURA_CONTROLABLE,
    SILLON_PARA_PACIENTE,
    SILLON_PARA_PSICOLOGO,
    ESCRITORIO,
    MESA_AUXILIAR,
    LIBRERO,
    SOFA,
    RELOJ_SILENCIOSO,
    PIZARRON,
    CONEXION_INTERNET,
    CAMARA_SEGURIDAD_EXTERNA,
    ENCHUFES_DISPONIBLES
}
